In [1]:
from catboost import CatBoostRegressor

In [2]:
model = CatBoostRegressor(iterations=200, learning_rate=0.05, depth=6, eval_metric='MAE', verbose=10, task_type='GPU', save_snapshot=True, snapshot_file='masoud', snapshot_interval=10)

In [3]:
model = model.load_model('catboost_reg.h5')

In [4]:
model

In [5]:
import pandas as pd
data_test = pd.read_csv('test.csv')
data_test.head()

,id,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,...,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14
0,4,A,B,A,A,A,A,A,A,B,...,0.281143,0.466591,0.317681,0.61229,0.34365,0.38016,0.377724,0.369858,0.704052,0.392562
1,6,A,B,A,B,A,A,A,A,B,...,0.836443,0.482425,0.443760,0.71330,0.51890,0.60401,0.689039,0.675759,0.453468,0.208045
2,9,A,B,A,B,B,A,B,A,B,...,0.718531,0.212308,0.325779,0.29758,0.34365,0.30529,0.245410,0.241676,0.258586,0.297232
3,12,A,A,A,A,B,A,A,A,A,...,0.397069,0.369930,0.342355,0.40028,0.33237,0.31480,0.348867,0.341872,0.592264,0.555955
4,15,B,A,A,A,A,B,A,A,A,...,0.302678,0.398862,0.391833,0.23688,0.43731,0.50556,0.359572,0.352251,0.301535,0.825823

In [6]:
data_test.drop(['id'], axis=1, inplace=True)

In [8]:
model.predict(data_test)

array([7.35473669, 7.63662319, 9.07606429, ..., 7.84087523, 6.78605325,
       8.23183276])

In [11]:
import numpy as np
np.exp(model.predict(data_test))

array([1563.58523195, 2072.73276933, 8743.48635302, ..., 2542.42907803,
        885.41215276, 3758.71628643])

In [12]:
data_test['loss'] = np.exp(model.predict(data_test))

In [13]:
data_test.head()

,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,cat10,...,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14,loss
0,A,B,A,A,A,A,A,A,B,A,...,0.466591,0.317681,0.61229,0.34365,0.38016,0.377724,0.369858,0.704052,0.392562,1563.585232
1,A,B,A,B,A,A,A,A,B,A,...,0.482425,0.443760,0.71330,0.51890,0.60401,0.689039,0.675759,0.453468,0.208045,2072.732769
2,A,B,A,B,B,A,B,A,B,B,...,0.212308,0.325779,0.29758,0.34365,0.30529,0.245410,0.241676,0.258586,0.297232,8743.486353
3,A,A,A,A,B,A,A,A,A,A,...,0.369930,0.342355,0.40028,0.33237,0.31480,0.348867,0.341872,0.592264,0.555955,4936.075866
4,B,A,A,A,A,B,A,A,A,A,...,0.398862,0.391833,0.23688,0.43731,0.50556,0.359572,0.352251,0.301535,0.825823,923.742497

In [ ]:
data_test.to_excel('prediction001.xlsx')

In [39]:
# MasoudKaviani.ir